name: Production Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to ECR
      run: |
        aws ecr get-login-password --region ap-southeast-2 \
        | docker login --username AWS --password-stdin 865950114072.dkr.ecr.ap-southeast-2.amazonaws.com

    - name: Build Docker Image
      run: |
        docker build -t day9 .

    - name: Tag Docker Image
      run: |
        docker tag day9:latest 865950114072.dkr.ecr.ap-southeast-2.amazonaws.com/day9:latest

    - name: Push Docker Image
      run: |
        docker push 865950114072.dkr.ecr.ap-southeast-2.amazonaws.com/day9:latest

    - name: Trigger ASG Instance Refresh
      run: |
        aws autoscaling start-instance-refresh \
        --auto-scaling-group-name asg-day9